language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- export RELEASE_ZIP_FILE=$(ls build/distributions/*.zip)
- echo "deploying $RELEASE_ZIP_FILE to GitHub releases"
jdk:
- oraclejdk8
script:
- "./gradlew clean build buildPlugin"
deploy:
  provider: releases
  api_key:
    secure: NV/MDCX2V5BtTGSK5cbfddi45pBVewyA4X0uwnr+L6QefMG7NVr27i5MI077ufZ5cE0UDhrqlTmbNYWgDuobTkmqE4xoslJsL8GWTjcLQGntBvEZFeLtWPsmJut2r16d0E1FGVmewA5ErguV2CnvhEW1FCb1gs2Rpma8J5K4HDXwbKsLP8y+qNrn3A0fVCTCTQccWUuTnWzeRIuJLFXaksJsGcR9TODrglsMx3akfzxF8YOIcVaYkBCb/XZnw6E7SuE/3XPQRnaGe0T8Oj/iVpXnRY7ZqomePTz8yjhrS+BVwGVrwyFKZctU7hyxjB5KQGSaJkEJNBpT9hmbeNqCV54AtHNv2ejYq3lyp7/n2M5dDvX2E6NhuaMTyGNcu21MF4iDu0SkNhEbcOnWRKoOMZL5qMZZqvMXlQaDLrnsS7NpbrbWs6zETyIaZANj1Ju/+AxAkniTW1Go1pZl0VGduuSa0Qh1bpQz91xGfFUrVNLOXG8vK9vl0ippBAqy2gUANWC3iySRA+p9CxxGuBwhvZ3hNeohYr+XyRqxg6WV5UwBOxd1+f6T8+gjyCnsefBdxREItey2xwMYp+XL3tVV3IQcZOyFaUBXpYllvxOiDLvGvKDTL/6yuhH71rsOOg6Lly8CmEVZVXdXXtoQ/8oqg9PiiVRjUGO1dhLobPPzZ8U=
  file: "${RELEASE_ZIP_FILE}"
  file_glob: true
  skip_cleanup: true
  on:
    repo: MontiSecArc/docker_generator
    tags: true
